config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from . import views

#import
from django.contrib.auth.decorators import login_required


app_name = 'main'

urlpatterns = [
    path('', views.BookList.as_view(),name='book_list'),
    # login
    path('signup/',views.sign_up,name='create_user'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    
    #user
    path('profile/', login_required(views.Profile.as_view()),name='profile'),
    path('published/', login_required(views.Published.as_view()),name='published'),
    path('registration/',login_required(views.Registration.as_view()),name='registration'),

    #book
    path('lend/', login_required(views.BookCreate),name='book_create'),
    path('booklend/<int:pk>/', login_required(views.BookLend),name='book_lend'),
    path('bookagain/<int:pk>/',login_required(views.BookAgain),name='book_again'),
    path('bookdelete/<int:pk>/',login_required(views.BookDelete),name='book_delete'),
    ]

main/models.py
from django.db import models

#import
import uuid 
from django.utils import timezone
from django.core.mail import send_mail
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, username, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.
    Username and password are required. Other fields are optional.
    """
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    first_name = models.CharField(_('first name'), max_length=30, blank=False)
    last_name = models.CharField(_('last name'), max_length=150, blank=False)
    email = models.EmailField(_('email address'), blank=False)
    borrow = models.BooleanField(default=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        #abstract = True #削除していないといけない

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)                                                      

class Category(models.Model):
    name = models.CharField('カテゴリ名',max_length=255, unique=True)
    def __str__(self):
        return self.name
class Book(models.Model):
    # 識別ID
    #id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) 
    
    # User情報
    lend_user = models.ForeignKey(User,on_delete=models.CASCADE) #貸出user 
    #borrow_user = models.OneToOneField(Borrow,on_delete=models.PROTECT,related_name='borrow_user',null=True,blank=True) #借出user
    #削除したアカウントの復元機能を実装する場合は、models.PROTECTがいいと思う   
    
    #書籍情報
    book_title = models.CharField(max_length=255) #題名
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='カテゴリ',blank=False)  #カテゴリ
    author_name = models.CharField(max_length=255,blank=True) #著者
    description = models.TextField(max_length=255,blank=True) #フレーズ
    created_at = models.DateTimeField('更新日',auto_now_add=True) #作成日
    #publishedDate = models.DateTimeField(max_length=12,blank=True) #出版日
    
    #貸出情報
    lend = models.BooleanField(default=True) #貸出判定
    user_name = models.CharField(max_length=255,blank=True) #借出希望user
    user_email= models.CharField(max_length=255,blank=True) #userメール
    
    def __str__(self):
        return self.book_title

main/forms.py
from django import forms
from .models import User,Book,Category
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

class SignUpForm(UserCreationForm):
    last_name = forms.CharField(
        max_length=30,
        label='苗字'
    )
    first_name = forms.CharField(
        max_length=30,
        label='名前'
    )
    email = forms.EmailField(
        max_length=255,
        label='Eメールアドレス'
    )
    class Meta:
        model = User
        fields = ('username', 'last_name', 'first_name',  'email', 'password1', 'password2', )
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class LendBookForm(forms.Form):
    isbn_code = forms.CharField(
        max_length=13,
        required=True,
        label='ISBNコード',
        help_text='書籍裏に記載の978から始まるコードを入力してください'
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['name'] ="keyword"

class PreviewForm(forms.ModelForm):
    book_title = forms.CharField(
            max_length=30,
            label='タイトル',
        )
    category = forms.ModelChoiceField(
        label = 'カテゴリー', 
        required = True,
        help_text = 'カテゴリを選択してください',
        queryset = Category.objects.all())
    author_name = forms.CharField(
            max_length=30,
            label='著者',            
        )
    description = forms.CharField(
        max_length=255,
        label = '説明',
        widget = forms.Textarea(attrs={'class' : 'input'})
    )
    
    class Meta:
        model = Book
        fields = ('book_title','category','author_name','description',)
        exclude = ('lend_user','borrow_user','lend','created_at')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['name'] ="keyword"

class PostSearchForm(forms.Form):
    key_word = forms.CharField(
        label = 'キーワード', required = False,
        widget = forms.TextInput(attrs={'class' : 'input'})
    )
    book = forms.ModelChoiceField(
        label = '投稿者', required = False,
        queryset = Book.objects.all()
    )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control mr-sm-2'
            field.widget.attrs['type'] ="search"
            field.widget.attrs['placeholder'] ="本を探す..."
            field.widget.attrs['aria-label'] ="本を探す..."

main/views.py
# Create your views here.
#import
import requests,json
from .models import Book,User
from django.db.models import Q
from django.views import generic
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.views import (LoginView, LogoutView)
from django.shortcuts import render, redirect,get_object_or_404
from .forms import LoginForm,UserCreationForm,SignUpForm,LendBookForm,PreviewForm,PostSearchForm

class Logout(LogoutView):
    template_name = 'contents/book_list.html'
class Profile(generic.TemplateView):
    model = User
    template_name = 'contents/profile.html'
class Published(generic.ListView):
    model = User
    template_name = 'contents/published.html'
class Login(LoginView):
    form_class = LoginForm
    template_name = 'entry/login.html'
class CreateUser(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'entry/sign_up.html'
    success_url = reverse_lazy('main:login')
class Registration(generic.CreateView):
    model = Book
    form_class = PreviewForm
    
    def form_valid(self,form):
        form = form.save(commit=False)
        form.lend_user_id = self.request.user.id
        form.save()
        messages.info(self.request,'書籍登録完了しました')
        return redirect('main:book_list')

class BookList(generic.ListView):
    model = Book
    ordering ='-created_at'
    template_name = 'contents/book_list.html'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        form = PostSearchForm(self.request.GET)
        if form.is_valid():
            book_title= form['key_word'].value()
            if book_title:
                queryset = queryset.filter(Q(book_title__icontains=book_title) | Q(description__icontains=book_title))
            return queryset

def sign_up(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request,'新規登録完了しました')
            return redirect('main:login')
    else:
        form = SignUpForm()
    return render(request, 'entry/sign_up.html', {'form': form})

def BookDelete(request,pk):
    book = get_object_or_404(Book,pk=pk)
    book.delete()
    messages.info(request,'書籍を削除しました')
    return redirect('main:published')

def BookAgain(request,pk):
    book,user= get_object_or_404(Book,pk=pk),get_object_or_404(User,username=book.user_name)
    book.lend, user.borrow = "True","True" 
    user.save(),book.save()
    messages.info(request,'再掲載しました')
    return redirect('main:published')

def BookLend(request,pk):
    print(request)
    book = get_object_or_404(Book,pk=pk)
    if book.lend:
        if request.user.borrow:
            user = get_object_or_404(User,pk=request.user.pk)
            user.borrow,book.lend = "False","False"
            book.user_name,book.user_email = request.user.username,request.user.email
            user.save(),book.save()
            messages.info(request,'申請が完了しました')
            return redirect('main:book_list')
        else:
            messages.error(request,'一度に借りられるのは一冊までです')
            return redirect('main:book_list')
    else:
        messages.error(request,'ただいま貸出中です再貸出までしばらくお待ちください')
        return redirect('main:book_list')

def BookCreate(request):
    if request.method == 'POST':
        form = LendBookForm(request.POST)
        if  form['isbn_code'].value():
            data = (requests.get(f"https://www.googleapis.com/books/v1/volumes?q=isbn:{form['isbn_code'].value()}")).json()
            if not data["totalItems"] == 0 :
                try:
                    description = data["items"][0]["volumeInfo"]["description"]
                except:
                    messages.error(request,'説明を取得できませんでした。出品者側で書き換えてください')
                    description = "未取得。"
                form = PreviewForm(initial = {
                    "description" : description,
                    'book_title': data["items"][0]["volumeInfo"]["title"],
                    'author_name':data["items"][0]["volumeInfo"]["authors"][0],
                    #"publication" : data["items"][0]["volumeInfo"]["publishedDate"],
                })
                return render(request,'entry/preview.html',{'form':form})
            else:
                messages.error(request,'書籍情報を取得できませんでした。')
                return render(request,'entry/lend.html',{'form':form})
    else:
        form = LendBookForm()
    return render(request, 'entry/lend.html', {'form':form})

main/templates/contents/book_list.html
{% extends "base.html" %}
{% block content %}
    {% if messages %}
    <ul class="alert alert-success" role="alert">
        {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {{ message }}
            </li>
        {% endfor %}
    </ul>
    {% endif %}
        <ul class="list-group list-group-flush">
            {% for book in book_list %}
                <li class="list-group-item list-group-item-secondary">
                    <div class="d-flex w-100 justify-content-between">
                        <h3 class="mb-1">{{ book.book_title }}</h3>
                        <small class="text-muted">カテゴリ: {{ book.category }}</small>
                    </div>
                        <small class="mb-1">
                            著者:{{ book.author_name }}
                        </small>
                        <p class="mb-1"><h5>{{ book.description }}</h5></p>
                    <div class="d-flex w-100 justify-content-between">
                                <small class="text-muted">投稿日:{{ book.created_at }}</small>    
                                {% if book.lend %}
                                        <h3><a class="btn btn-primary" href="{% url 'main:book_lend' book.pk %}" role="button">申請する</a></h3>
                                    {% else %}
                                        <h3><a class="btn btn-dark" href="{% url 'main:book_lend' book.pk %}" role="button">貸出中</a></h3>
                                    {% csrf_token %}
                                {% endif %}
                    </div>
                </li>
            {% endfor %}
        </ul>        
{% endblock %}

main/templates/contents/profile.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="POST">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                <h2 class="text-center">登録情報</h2>
                    <p>
                        <label>ユーザー名:</label>
                        <font>{{ user.username }}</font><br>
                        <label>苗字:</label>
                        <font>{{ user.first_name }}</font><br>
                        <label>名前:</label>
                        <font>{{ user.last_name }}</font><br>
                        <label>メールアドレス:</label>
                        <font>{{ user.email }}</font><br>
                    </p>
                <div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

main/templates/contents/published.html
{% extends "base.html" %}
{% block content %}
    {% for book in user.book_set.all %}
        {% if messages %}
            <ul class="alert alert-success" role="alert">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    <form data-deleteurl="">
        <ul class="list-group">
            <li class="list-group-item list-group-item-secondary " data-toggle="modal" data-target="#target">
                <div class="d-flex w-100 justify-content-between">
                        <h3 class="mb-1">{{ book.book_title }}</h3>
                        <small class="text-muted">カテゴリ: {{ book.category }}</small>
                </div>
                    <small class="mb-1">出版日:{{ book.publishedDate }}</small>
                    <p class="mb-1"><h5>{{ book.description }}</h5></p>
                <div class="d-flex w-100 justify-content-between">
                    <small class="text-muted">投稿日:{{ book.created_at }}</small>
                    {% if not book.lend %}
                    <div>
                        <small class="text-muted">希望者:{{ book.user_name }}</small><br>
                        <small class="text-muted">連絡先:{{ book.user_email }}</small>
                    </div>
                        {% endif %}
                    {% if book.lend %}
                    <div>    
                        <h3><span class="badge badge-primary">受付中</span></h3>
                        <a href="{% url 'main:book_delete' book.pk %}" class="badge badge-danger">削除する</a>
                    </div>
                    {% else %}
                    <div>
                        <h3><span class="badge badge-primary">希望者あり</span></h3>
                        <a href="{% url 'main:book_delete' book.pk %}" class="badge badge-danger">削除する</a>
                        <a href="{% url 'main:book_again' book.pk %}" class="badge badge-danger">再掲載する</a>
                    </div>
                            {% endif %}
            </li>
        </ul>
        </form>
    {% endfor %}
{% endblock %}

main/templates/contents/search_form.html
<form action="{% url 'main:book_list' %}" method="GET" class="form-inline my-2 my-md-0">
    <div class="field">
        <div class="control">
            {{ form.key_word }}
        </div>
    </div>
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">検索</button>
</form>